title: Proxer Essentials
description: > # this means to ignore newlines until "baseurl:"
  Nützlicher Erweiterungen für Proxer die jeder braucht

theme: jekyll-theme-cayman

#Install-Button
show_install: true
install_url: https://openuserjs.org/install/Blue.Reaper/Proxer_Essentials.user.js
